release: main.cpp edge.h graph.h 
	g++-6 -O3 -std=c++14 -Wall -Wextra main.cpp graph.cpp -o release

debug: main.cpp graph.cpp edge.h graph.h 
	g++-6 -g -std=c++14 -Wall -Wextra main.cpp graph.cpp -o debug

